### ISSUE TITLE
HISTFILE and REDO_HISTORY_PATH not found

### ISSUE THREAD

**Issue by joshuabremerdexcom** [barthr/redo#2] opened 2022-04-01 15:47 UTC
This one is weird. You can see that the ENV is set...but it doesn't load until I explicitly set it. I may be doing something wrong...but this is confusing to me.

![image](https://user-images.githubusercontent.com/59564543/161297622-09807c25-e6e1-483c-9145-464b3fdf407c.png)

This works too: 

![image](https://user-images.githubusercontent.com/59564543/161297911-5eca6756-5dcd-41ab-88d9-1cd820198c42.png)

Ideas?

**Comment by barthr** [comment] 2022-04-01 15:51
I think the problem is that HISTFILE is a default env variable which I'm not able to read correctly. By explicitly setting it, it becomes a variable locally to the current shell, which the process is able to read. This is clearly a bug, as a workaround you can set this in your zshrc:

```
export HISTFILE="$HOME/.zsh_history"
```

**Comment by joshuabremerdexcom** [comment] 2022-04-01 15:52
Absolutely. Thanks for making this and putting it in Hacker news. Really great idea.

**Comment by barthr** [comment] 2022-04-01 15:54
Thank you! Currently the tool is a bit alpha, i've been using it myself for some days and it is expected to have some bugs :)

**Comment by chris-aeviator** [comment] 2022-04-02 10:35
facing the same on arch linux + zsh

**Comment by DimitriGilbert** [comment] 2022-04-02 14:04
same problem here on mint + zsh
the provided fix worked but I had another error :
```bash
REDO_EDITOR or EDITOR env variable must be set
```

It was fixed by adding this line to ~/.zshrc
```bash
export REDO_EDITOR="<your favorite editor>"
```

**Comment by barthr** [comment] 2022-04-02 14:12
So apparently any "default" variable from the environment can't be read from Go. Thanks for reporting, I will look into this and try to update the documentation accordingly

**Comment by DimitriGilbert** [comment] 2022-04-02 14:30
Looks like it apparently. 
If it helps I am using oh-my-zsh, maybe that'll help.

Actually, Thank you for this tool.
I had a similar idea a while back but never got around to make it and you made something far better that I would have so :+1:

**Comment by barthr** [comment] 2022-04-25 20:19
I think the only way to do this is to export the EDITOR and HISTFILE variable. Since they are hidden by default (not exported). This is slightly inconvenient but luckily a one time setup

**Closed by barthr** 2022-04-25 20:19 UTC
Labels: bug
